- name: create directories for fluent-bit
  file:
    path: "{{ FLUENT_BIT_DIRECTORY }}/{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - config

- name: create fluent-bit config file
  template:
    src: fluent-bit.conf.j2
    dest: "{{ FLUENT_BIT_DIRECTORY }}/config/fluent-bit.conf"

- name: create docker images directory
  file:
    path: "{{ DOCKER_IMAGE_DIRECTORY }}"
    state: directory
    mode: 0777

- name: create history_to_syslog.sh
  template:
    src: history_to_syslog.sh.j2
    dest: "/etc/profile.d/history_to_syslog.sh"

- name: config rsyslog for bash_history 
  lineinfile:
    path: /etc/rsyslog.conf
    line: 'local1.notice     /var/log/bash_history/bash_command.log'

- name: create bash_command file
  copy:
    content: ""
    dest: "/var/log/bash_history/bash_command.log"
    force: no
    owner: root
    mode: 0600

- name: copy rsyslog.conf 
  template: 
    src: rsyslog.conf.j2
    dest: "/etc/rsyslog.conf"


- name: restart rsyslog
  systemd: state=restarted name=rsyslog

- name: set logrorate
  template: 
    src: logratate.j2
    dest: "/etc/logrotate.d/commands"

- name: enable lograte 
  shell: "/usr/sbin/logrotate /etc/logrotate.d/commands"


- name: copy docker image file
  get_url:
    url: "{{ MONITORING_WEB_REPO }}/docker_images/fluent-bit.tar"
    dest: "{{ DOCKER_IMAGE_DIRECTORY }}/fluent-bit.tar"

- name: Load image
  docker_image:
    name: docker.io/fluent/fluent-bit
    load_path: "{{ DOCKER_IMAGE_DIRECTORY }}/fluent-bit.tar"

- name: Create fluent-bit container
  docker_container:
    name: fluent-bit
    image: "docker.io/fluent/fluent-bit:latest"
    network_mode: host
    restart: yes
    restart_policy: unless-stopped
    user: root
    privileged: no
    volumes:
      - "{{ FLUENT_BIT_DIRECTORY }}/config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:Z"
      - "/var/log/cron:/var/log/cron:Z"
      - "/var/log/haproxy.log:/var/log/haproxy.log:Z"
      - "/var/log/messages:/var/log/messages:Z"
      - "/var/log/bash_history/bash_command.log:/var/log/bash_history/bash_command.log:Z"
      - "/var/log/ceph:/var/log/ceph:Z"
      - "/var/lib/docker/volumes/kolla_logs/_data/haproxy:/var/log/haproxy:Z"
      - "/var/lib/docker/volumes/kolla_logs/_data/nova:/var/log/nova:Z"
      - "/var/lib/docker/volumes/kolla_logs/_data/cinder:/var/log/cinder:Z"
      - "/var/lib/docker/volumes/kolla_logs/_data/glance:/var/log/glance:Z"
      - "/var/lib/docker/volumes/kolla_logs/_data/horizon:/var/log/horizon:Z"
      - "/var/lib/docker/volumes/kolla_logs/_data/keystone:/var/log/keystone:Z"
      - "/var/lib/docker/volumes/kolla_logs/_data/mariadb:/var/log/mariadb:Z"
      - "/var/lib/docker/volumes/kolla_logs/_data/neutron:/var/log/neutron:Z"

