#- name: install docker local repository
#  yum_repository:
#    name: docker-ce-stable
#    description: Docker CE Stable - $basearch
#    baseurl: "{{ docker_local_repo }}"
#    gpgcheck: no


- name: install docker packages
  yum:
    name: "{{ docker_package_name }}"
    state: present


- name: create directory /etc/docker
  file:
    path: /etc/docker
    state: directory

- name: configure to use overlay2 storage driver
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: configure /etc/sysconfig/docker
  template:
    src: sysconfig_docker.j2
    dest: /etc/sysconfig/docker

- name: configure /usr/lib/systemd/system/docker.service
  template:
    src: systemd_docker.j2
    dest: /usr/lib/systemd/system/docker.service

- name: start docker
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: True
