---
- name: ZABBIX Agent delete
  hosts: zabbix_agent_master
  become: true

  tasks:
  - name: stop/disabled for zabbix_agent
    systemd:
      name: zabbix-agent.service
      state: stopped
      enabled: False

  - name: remove zabbix agent
    shell: yum remove zabbix-agent -y
 
  - name: destroy zabbix agent file
    file:
      state: absent
      path: "/etc/zabbix"

   
