---
- name: GRAFANA delete
  hosts: grafana_master
  become: true

  tasks:
  - name: down docker-compose
    shell: "{{ PIP_VIRTUALENV_DIRECTORY }}/bin/docker-compose down"
    args:
      chdir: "{{ GRAFANA_DIRECTORY }}"

  - name: clean artifact path
    file:
      state: absent
      path: "{{ GRAFANA_DIRECTORY }}"
