---
- name: elastic_stack delete
  hosts: elastic_master
  become: true

  tasks:
  - name: down docker-compose
    shell: "{{ PIP_VIRTUALENV_DIRECTORY }}/bin/docker-compose down"
    args:
      chdir: "{{ ELASTICSEARCH_DIRECTORY }}"

  - name: clean artifact path
    file:
      state: absent
      path: "{{ ELASTICSEARCH_DIRECTORY }}"
